file.open("config_server.lua", "w+")
file.write([[print("ciao")]])
file.close()

srv=net.createServer(net.TCP)
srv:listen(80,function(conn)
conn:on("receive",function(conn,payload)
print(payload)
conn:send("HTTP/1.1 200 OK\r\n")
conn:send("Server: ESP8266 Lua\r\n")
conn:send("Access-Control-Allow-Origin: http://PublicIP\r\n")
conn:send("Access-Control-Allow-Methods: GET\r\n")
conn:send("Keep-Alive: *\r\n")
conn:send("Connection: Keep-Alive\r\n")
conn:send("Accept: */*\r\n")
conn:send("User-Agent: Mozilla/4.0\r\n")
conn:send("\r\n")
conn:close()
end)
end)
