file.open("config.lua", "r")
ssid = file.read('\n')
pass = file.read('\n')
name = file.read('\n')
token = file.read('\n')
ssid = string.gsub(ssid, "\n", "")
pass = string.gsub(pass, "\n", "")
name = string.gsub(name, "\n", "")
token = string.gsub(token, "n", "")
file.close()
print(ssid..pass..name..token)
--print("pass: "..'"'..pass..'"')
--print("name: "..name)
--print("token: "..token)
wifi.setmode(wifi.STATION)
wifi.sta.config(ssid, pass)
ip = wifi.sta.connect()
print(ip)