file.open("config.lua", "r")
a = file.read('\n')
b = file.read('\n')
c = file.read('\n')
d = file.read('\n')
file.close()
a = string.gsub(a, "\n", "")
print("a: "..a)
print("b: "..b)
print("c: "..c)
print("d: "..d)