file.open("registrazione.lua", "w")
file.write([[
ip = wifi.sta.getip()
print(wifi.sta.getmac())
conn=net.createConnection(net.TCP, 0)  
conn:on("receive", function(conn, payload) print(payload) end) 
conn:connect(443,'192.168.0.8')  
conn:send("GET /public_api.php?task=moduleReg&name="..name.."&IP="..ip.."&token="..token.." HTTP/1.1\r\n") 
conn:send("Host: prowl.weks.net\r\n")  
conn:send("Accept: */*\r\n") 
conn:send("User-Agent: Mozilla/4.0 (compatible; esp8266 Lua; Windows NT 5.1)\r\n") 
conn:send("\r\n")  
dofile("first_setup.lua")
]])
file.close()